<!DOCTYPE html>
<html lang="pl">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <title>DashBoard</title>
    <link rel="stylesheet" href="public/styles/dashboard.css">
</head>

<body>
    <nav>
        <div class="navigation-bar">
            <div>Absolute Cinema</div>
            <div>Lokalizacja</div>
            <div>Zaloguj/Moje Konto</div>
            <div>Kontakt</div>
            <input id="search-bar" type="text" placeholder="🔎 Szukaj">
        </div>
    </nav>

    <div class="offer-section">
        <input type="radio" name="tab_set" id="tab-screen" checked>
        <input type="radio" name="tab_set" id="tab-soon">
        <input type="radio" name="tab_set" id="tab-gastro">

        <div class="cinema-offer-bar">
            <label for="tab-screen">Na Ekranie</label>
            <label for="tab-soon">Wkrótce</label>
            <label for="tab-gastro">Oferta Gastronomiczna</label>
        </div>

        <div class="tab-content-container">
            <div id="content-screen" class="tab-panel">
                <p>Kafelki filmów NA EKRANIE</p>
            </div>

            <div id="content-soon" class="tab-panel">
                <p>Kafelki filmów WKRÓTCE</p>
            </div>
    
            <div id="content-gastro" class="tab-panel">
                <p>Kafelki OFERTA GASTRONOMICZNA</p>
            </div>
        </div>
    </div>
</body>
</html>